LoadedData = load('Test.mat');
kinectParams = cameraParameters('IntrinsicMatrix', double(LoadedData.IntrinicMatrix), ...
                                'RadialDistortion', double(LoadedData.RadialDistortion), ...
                                'TangentialDistortion', double(LoadedData.TangentialDistortion), ...
                                'RotationVectors', double(LoadedData.RotationVectors),  ...
                                'TranslationVectors', double(LoadedData.TranslationVectors), ...
                                'WorldPoints', double(LoadedData.WorldPoints));
                            
K = kinectParams.IntrinsicMatrix
R = kinectParams.RotationMatrices(:,:,1)
T = kinectParams.TranslationVectors(1,:)
WorldPoint = [kinectParams.WorldPoints(1,:) 0]

cameraPoint = K*(R*WorldPoint' + T')