% kinectParams = cameraParameters("IntrinsicMatrix",IntrinicMatrix, ...
%                                 "RadialDistortion", RadialDistortion, ...
%                                 "TangentialDistortion", TangentialDistortion, ...
%                                 "ImageSize", ImageSize, ...,
%                                 "RotationVectors", cameraParams.RotationVectors(1,:),  ...
%                                 "TranslationVectors", cameraParams.TranslationVectors(1,:), ...
%                                 "WorldPoints", double(WorldPoints) ...
%                                 )
load('Test.mat')
kinectParams = cameraParameters('IntrinsicMatrix', double(IntrinicMatrix), ...
                                'RadialDistortion', double(RadialDistortion), ...
                                'TangentialDistortion', double(TangentialDistortion), ...
                                'RotationVectors', double(RotationVectors),  ...
                                'TranslationVectors', double(TranslationVectors), ...
                                'WorldPoints', double(WorldPoints) ...
                                )
showExtrinsics(kinectParams)

